// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: track.proto

package utm

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TrafficCollector_CollectTraffic_FullMethodName = "/utm.TrafficCollector/CollectTraffic"
)

// TrafficCollectorClient is the client API for TrafficCollector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// grpc server is assumed to be on platform side
type TrafficCollectorClient interface {
	CollectTraffic(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Track, emptypb.Empty], error)
}

type trafficCollectorClient struct {
	cc grpc.ClientConnInterface
}

func NewTrafficCollectorClient(cc grpc.ClientConnInterface) TrafficCollectorClient {
	return &trafficCollectorClient{cc}
}

func (c *trafficCollectorClient) CollectTraffic(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Track, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TrafficCollector_ServiceDesc.Streams[0], TrafficCollector_CollectTraffic_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Track, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrafficCollector_CollectTrafficClient = grpc.ClientStreamingClient[Track, emptypb.Empty]

// TrafficCollectorServer is the server API for TrafficCollector service.
// All implementations must embed UnimplementedTrafficCollectorServer
// for forward compatibility.
//
// grpc server is assumed to be on platform side
type TrafficCollectorServer interface {
	CollectTraffic(grpc.ClientStreamingServer[Track, emptypb.Empty]) error
	mustEmbedUnimplementedTrafficCollectorServer()
}

// UnimplementedTrafficCollectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTrafficCollectorServer struct{}

func (UnimplementedTrafficCollectorServer) CollectTraffic(grpc.ClientStreamingServer[Track, emptypb.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method CollectTraffic not implemented")
}
func (UnimplementedTrafficCollectorServer) mustEmbedUnimplementedTrafficCollectorServer() {}
func (UnimplementedTrafficCollectorServer) testEmbeddedByValue()                          {}

// UnsafeTrafficCollectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrafficCollectorServer will
// result in compilation errors.
type UnsafeTrafficCollectorServer interface {
	mustEmbedUnimplementedTrafficCollectorServer()
}

func RegisterTrafficCollectorServer(s grpc.ServiceRegistrar, srv TrafficCollectorServer) {
	// If the following call pancis, it indicates UnimplementedTrafficCollectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TrafficCollector_ServiceDesc, srv)
}

func _TrafficCollector_CollectTraffic_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TrafficCollectorServer).CollectTraffic(&grpc.GenericServerStream[Track, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TrafficCollector_CollectTrafficServer = grpc.ClientStreamingServer[Track, emptypb.Empty]

// TrafficCollector_ServiceDesc is the grpc.ServiceDesc for TrafficCollector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrafficCollector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "utm.TrafficCollector",
	HandlerType: (*TrafficCollectorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CollectTraffic",
			Handler:       _TrafficCollector_CollectTraffic_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "track.proto",
}
