// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: track.proto

package utm

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Emitter int32

const (
	Emitter_EMITTER_UNKNOWN             Emitter = 0 // unknown
	Emitter_EMITTER_LIGHT_AIRCRAFT      Emitter = 1 // light aircraft <= 15500 lbs
	Emitter_EMITTER_SMALL_AIRCRAFT      Emitter = 2 // 15500 lbs < small aircraft < 75000 lbs
	Emitter_EMITTER_MEDIUM_AIRCRAFT     Emitter = 3 // 75000 lbs < medium aircraft < 300000 lbs
	Emitter_EMITTER_LARGE_AIRCRAFT      Emitter = 4 // high vortex, large aircraft
	Emitter_EMITTER_HEAVY_AIRCAFT       Emitter = 5 // >= 300000 lbs
	Emitter_EMITTER_HIGHLY_MANUEVERABLE Emitter = 6 // highly maneuverable (5g capability) and high speed (400+ knots cruise)
	// reserved 7 to 9;
	Emitter_EMITTER_ROTORCRAFT       Emitter = 10 // helicopter / rotocraft
	Emitter_EMITTER_GLIDER           Emitter = 11 // glider / sailplane
	Emitter_EMITTER_LIGHTER_THAN_AIR Emitter = 12 // lighter than air / blimp
	Emitter_EMITTER_UAV              Emitter = 13 // unmanned aerial vehicle
	Emitter_EMITTER_SPACE            Emitter = 14 // space / transatmospheric vehicle
	Emitter_EMITTER_ULTRALIGHT       Emitter = 15 // ultralight / hang glider / paraglider
	Emitter_EMITTER_PARACHUTIST      Emitter = 16 // parachutist / skydiver
	// reserved 17 to 19;
	Emitter_EMITTER_SFC_EMERGENCY_VEHICLE Emitter = 20 // surface emergency vehicle
	Emitter_EMITTER_SFC_SERVICE_VEHICLE   Emitter = 21 // surface service vehicle
	Emitter_EMITTER_SFC_OBSTACLE          Emitter = 22 // fixed ground or tethered obstacle
	Emitter_EMITTER_SFC_OBSTACLE_CLUSTER  Emitter = 23 // cluster obstacle
	Emitter_EMITTER_SFC_OBSTACLE_LINE     Emitter = 24 // line obstacle
)

// Enum value maps for Emitter.
var (
	Emitter_name = map[int32]string{
		0:  "EMITTER_UNKNOWN",
		1:  "EMITTER_LIGHT_AIRCRAFT",
		2:  "EMITTER_SMALL_AIRCRAFT",
		3:  "EMITTER_MEDIUM_AIRCRAFT",
		4:  "EMITTER_LARGE_AIRCRAFT",
		5:  "EMITTER_HEAVY_AIRCAFT",
		6:  "EMITTER_HIGHLY_MANUEVERABLE",
		10: "EMITTER_ROTORCRAFT",
		11: "EMITTER_GLIDER",
		12: "EMITTER_LIGHTER_THAN_AIR",
		13: "EMITTER_UAV",
		14: "EMITTER_SPACE",
		15: "EMITTER_ULTRALIGHT",
		16: "EMITTER_PARACHUTIST",
		20: "EMITTER_SFC_EMERGENCY_VEHICLE",
		21: "EMITTER_SFC_SERVICE_VEHICLE",
		22: "EMITTER_SFC_OBSTACLE",
		23: "EMITTER_SFC_OBSTACLE_CLUSTER",
		24: "EMITTER_SFC_OBSTACLE_LINE",
	}
	Emitter_value = map[string]int32{
		"EMITTER_UNKNOWN":               0,
		"EMITTER_LIGHT_AIRCRAFT":        1,
		"EMITTER_SMALL_AIRCRAFT":        2,
		"EMITTER_MEDIUM_AIRCRAFT":       3,
		"EMITTER_LARGE_AIRCRAFT":        4,
		"EMITTER_HEAVY_AIRCAFT":         5,
		"EMITTER_HIGHLY_MANUEVERABLE":   6,
		"EMITTER_ROTORCRAFT":            10,
		"EMITTER_GLIDER":                11,
		"EMITTER_LIGHTER_THAN_AIR":      12,
		"EMITTER_UAV":                   13,
		"EMITTER_SPACE":                 14,
		"EMITTER_ULTRALIGHT":            15,
		"EMITTER_PARACHUTIST":           16,
		"EMITTER_SFC_EMERGENCY_VEHICLE": 20,
		"EMITTER_SFC_SERVICE_VEHICLE":   21,
		"EMITTER_SFC_OBSTACLE":          22,
		"EMITTER_SFC_OBSTACLE_CLUSTER":  23,
		"EMITTER_SFC_OBSTACLE_LINE":     24,
	}
)

func (x Emitter) Enum() *Emitter {
	p := new(Emitter)
	*p = x
	return p
}

func (x Emitter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Emitter) Descriptor() protoreflect.EnumDescriptor {
	return file_track_proto_enumTypes[0].Descriptor()
}

func (Emitter) Type() protoreflect.EnumType {
	return &file_track_proto_enumTypes[0]
}

func (x Emitter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Emitter.Descriptor instead.
func (Emitter) EnumDescriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{0}
}

type Altitude_Reference int32

const (
	Altitude_REFERENCE_UNKNOWN       Altitude_Reference = 0 // The unknown reference.
	Altitude_REFERENCE_ELLIPSOID     Altitude_Reference = 1 // References the hypothetical equipotential gravitational surface.
	Altitude_REFERENCE_GEOID         Altitude_Reference = 2 // References and approximates the mean sea level.
	Altitude_REFERENCE_SURFACE       Altitude_Reference = 3 // References the actual height of the surface.
	Altitude_REFERENCE_EXTERNAL      Altitude_Reference = 4 // References an external measurement or estimate.
	Altitude_REFERENCE_STANDARD_BARO Altitude_Reference = 5 // References a flight level (FL).
	Altitude_REFERENCE_LOCAL_BARO    Altitude_Reference = 6 // References a local MSL.
)

// Enum value maps for Altitude_Reference.
var (
	Altitude_Reference_name = map[int32]string{
		0: "REFERENCE_UNKNOWN",
		1: "REFERENCE_ELLIPSOID",
		2: "REFERENCE_GEOID",
		3: "REFERENCE_SURFACE",
		4: "REFERENCE_EXTERNAL",
		5: "REFERENCE_STANDARD_BARO",
		6: "REFERENCE_LOCAL_BARO",
	}
	Altitude_Reference_value = map[string]int32{
		"REFERENCE_UNKNOWN":       0,
		"REFERENCE_ELLIPSOID":     1,
		"REFERENCE_GEOID":         2,
		"REFERENCE_SURFACE":       3,
		"REFERENCE_EXTERNAL":      4,
		"REFERENCE_STANDARD_BARO": 5,
		"REFERENCE_LOCAL_BARO":    6,
	}
)

func (x Altitude_Reference) Enum() *Altitude_Reference {
	p := new(Altitude_Reference)
	*p = x
	return p
}

func (x Altitude_Reference) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Altitude_Reference) Descriptor() protoreflect.EnumDescriptor {
	return file_track_proto_enumTypes[1].Descriptor()
}

func (Altitude_Reference) Type() protoreflect.EnumType {
	return &file_track_proto_enumTypes[1]
}

func (x Altitude_Reference) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Altitude_Reference.Descriptor instead.
func (Altitude_Reference) EnumDescriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{3, 0}
}

// track to be used as observation for amoebas
type Track struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Raw   []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"` // raw message
	// sender
	ProviderId      string `protobuf:"bytes,11,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`                // Name of the facility that reported the observation.
	SourceId        string `protobuf:"bytes,12,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`                      // sensor source identifiers (traffic)
	AsterixCategory string `protobuf:"bytes,14,opt,name=asterix_category,json=asterixCategory,proto3" json:"asterix_category,omitempty"` // asterix category
	// identification informations
	TrackId                string  `protobuf:"bytes,21,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`                                                // source specific track identifier for traffic - aka - Track Number
	Callsign               string  `protobuf:"bytes,22,opt,name=callsign,proto3" json:"callsign,omitempty"`                                                             // Callsign of the vehicle.
	IcaoAircraftDescriptor string  `protobuf:"bytes,23,opt,name=icao_aircraft_descriptor,json=icaoAircraftDescriptor,proto3" json:"icao_aircraft_descriptor,omitempty"` // Aircraft-specific ICAO-information.
	AircraftType           string  `protobuf:"bytes,24,opt,name=aircraft_type,json=aircraftType,proto3" json:"aircraft_type,omitempty"`                                 // aircraft_type
	EmitterCategory        Emitter `protobuf:"varint,25,opt,name=emitter_category,json=emitterCategory,proto3,enum=utm.Emitter" json:"emitter_category,omitempty"`      // emitter category
	// times
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,31,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // The time when the update was observed by the client.
	// measures
	Position        *Coordinate `protobuf:"bytes,41,opt,name=position,proto3" json:"position,omitempty"`                                          // latitude, longitude, altitude
	VelocityMs      *Velocity   `protobuf:"bytes,42,opt,name=velocity_ms,json=velocityMs,proto3" json:"velocity_ms,omitempty"`                    // Velocity of the vehicle expressed as XYZ vectors, in [m/s]
	GroudSpeedMs    float64     `protobuf:"fixed64,43,opt,name=groud_speed_ms,json=groudSpeedMs,proto3" json:"groud_speed_ms,omitempty"`          // Speed of the vehicle relative to the ground in meters per second
	VerticalSpeedMs float64     `protobuf:"fixed64,44,opt,name=vertical_speed_ms,json=verticalSpeedMs,proto3" json:"vertical_speed_ms,omitempty"` // Vertical speed of the vehicle, in meters per second.
	HeadingDegrees  float64     `protobuf:"fixed64,45,opt,name=heading_degrees,json=headingDegrees,proto3" json:"heading_degrees,omitempty"`      // heading of the plane (=course), angle from True North, 0-360, counterclockwise
	// accuracy
	Accuracy      *Track_Accuracy `protobuf:"bytes,50,opt,name=accuracy,proto3,oneof" json:"accuracy,omitempty"` // measurement accuracies
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Track) Reset() {
	*x = Track{}
	mi := &file_track_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{0}
}

func (x *Track) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *Track) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *Track) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Track) GetAsterixCategory() string {
	if x != nil {
		return x.AsterixCategory
	}
	return ""
}

func (x *Track) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *Track) GetCallsign() string {
	if x != nil {
		return x.Callsign
	}
	return ""
}

func (x *Track) GetIcaoAircraftDescriptor() string {
	if x != nil {
		return x.IcaoAircraftDescriptor
	}
	return ""
}

func (x *Track) GetAircraftType() string {
	if x != nil {
		return x.AircraftType
	}
	return ""
}

func (x *Track) GetEmitterCategory() Emitter {
	if x != nil {
		return x.EmitterCategory
	}
	return Emitter_EMITTER_UNKNOWN
}

func (x *Track) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Track) GetPosition() *Coordinate {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Track) GetVelocityMs() *Velocity {
	if x != nil {
		return x.VelocityMs
	}
	return nil
}

func (x *Track) GetGroudSpeedMs() float64 {
	if x != nil {
		return x.GroudSpeedMs
	}
	return 0
}

func (x *Track) GetVerticalSpeedMs() float64 {
	if x != nil {
		return x.VerticalSpeedMs
	}
	return 0
}

func (x *Track) GetHeadingDegrees() float64 {
	if x != nil {
		return x.HeadingDegrees
	}
	return 0
}

func (x *Track) GetAccuracy() *Track_Accuracy {
	if x != nil {
		return x.Accuracy
	}
	return nil
}

type Velocity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"` // The velocity along the X axis.
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"` // The velocity along the Y axis.
	Z             float64                `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"` // The velocity along the Z axis. (i.e vertical speed, expected in m.m.s-1.s-1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Velocity) Reset() {
	*x = Velocity{}
	mi := &file_track_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Velocity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Velocity) ProtoMessage() {}

func (x *Velocity) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Velocity.ProtoReflect.Descriptor instead.
func (*Velocity) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{1}
}

func (x *Velocity) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Velocity) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Velocity) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Coordinate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LatitudeDegrees  float64                `protobuf:"fixed64,1,opt,name=latitude_degrees,json=latitudeDegrees,proto3" json:"latitude_degrees,omitempty"`    // The latitude component of this coordinate.
	LongitudeDegrees float64                `protobuf:"fixed64,2,opt,name=longitude_degrees,json=longitudeDegrees,proto3" json:"longitude_degrees,omitempty"` // The longitude component of this coordinate.
	Altitude         *Altitude              `protobuf:"bytes,3,opt,name=altitude,proto3" json:"altitude,omitempty"`                                           // The altitude component of this coordinate.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_track_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{2}
}

func (x *Coordinate) GetLatitudeDegrees() float64 {
	if x != nil {
		return x.LatitudeDegrees
	}
	return 0
}

func (x *Coordinate) GetLongitudeDegrees() float64 {
	if x != nil {
		return x.LongitudeDegrees
	}
	return 0
}

func (x *Coordinate) GetAltitude() *Altitude {
	if x != nil {
		return x.Altitude
	}
	return nil
}

// Altitude models height over reference point.
type Altitude struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meters        float64                `protobuf:"fixed64,3,opt,name=meters,proto3" json:"meters,omitempty"`                                  // The actual value.
	Reference     Altitude_Reference     `protobuf:"varint,4,opt,name=reference,proto3,enum=utm.Altitude_Reference" json:"reference,omitempty"` // The reference for the altitude of this coordinate.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Altitude) Reset() {
	*x = Altitude{}
	mi := &file_track_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Altitude) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Altitude) ProtoMessage() {}

func (x *Altitude) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Altitude.ProtoReflect.Descriptor instead.
func (*Altitude) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{3}
}

func (x *Altitude) GetMeters() float64 {
	if x != nil {
		return x.Meters
	}
	return 0
}

func (x *Altitude) GetReference() Altitude_Reference {
	if x != nil {
		return x.Reference
	}
	return Altitude_REFERENCE_UNKNOWN
}

type Track_Accuracy struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PositionX          float64                `protobuf:"fixed64,1,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"` // Estimated Accuracy Of Track Position - X - horizontal dilution
	PositionY          float64                `protobuf:"fixed64,2,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"` // Estimated Accuracy Of Track Position - Y - vertical dilution
	Latitude           float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude          float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	GeometricAltitude  float64                `protobuf:"fixed64,5,opt,name=geometric_altitude,json=geometricAltitude,proto3" json:"geometric_altitude,omitempty"`
	BarometricAltitude float64                `protobuf:"fixed64,6,opt,name=barometric_altitude,json=barometricAltitude,proto3" json:"barometric_altitude,omitempty"`
	VelocityX          float64                `protobuf:"fixed64,7,opt,name=velocity_x,json=velocityX,proto3" json:"velocity_x,omitempty"`
	VelocityY          float64                `protobuf:"fixed64,8,opt,name=velocity_y,json=velocityY,proto3" json:"velocity_y,omitempty"`
	AccelerationX      float64                `protobuf:"fixed64,9,opt,name=acceleration_x,json=accelerationX,proto3" json:"acceleration_x,omitempty"`
	AccelerationY      float64                `protobuf:"fixed64,10,opt,name=acceleration_y,json=accelerationY,proto3" json:"acceleration_y,omitempty"`
	RateOfClimb        float64                `protobuf:"fixed64,11,opt,name=rate_of_climb,json=rateOfClimb,proto3" json:"rate_of_climb,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Track_Accuracy) Reset() {
	*x = Track_Accuracy{}
	mi := &file_track_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track_Accuracy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track_Accuracy) ProtoMessage() {}

func (x *Track_Accuracy) ProtoReflect() protoreflect.Message {
	mi := &file_track_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track_Accuracy.ProtoReflect.Descriptor instead.
func (*Track_Accuracy) Descriptor() ([]byte, []int) {
	return file_track_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Track_Accuracy) GetPositionX() float64 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *Track_Accuracy) GetPositionY() float64 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *Track_Accuracy) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Track_Accuracy) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Track_Accuracy) GetGeometricAltitude() float64 {
	if x != nil {
		return x.GeometricAltitude
	}
	return 0
}

func (x *Track_Accuracy) GetBarometricAltitude() float64 {
	if x != nil {
		return x.BarometricAltitude
	}
	return 0
}

func (x *Track_Accuracy) GetVelocityX() float64 {
	if x != nil {
		return x.VelocityX
	}
	return 0
}

func (x *Track_Accuracy) GetVelocityY() float64 {
	if x != nil {
		return x.VelocityY
	}
	return 0
}

func (x *Track_Accuracy) GetAccelerationX() float64 {
	if x != nil {
		return x.AccelerationX
	}
	return 0
}

func (x *Track_Accuracy) GetAccelerationY() float64 {
	if x != nil {
		return x.AccelerationY
	}
	return 0
}

func (x *Track_Accuracy) GetRateOfClimb() float64 {
	if x != nil {
		return x.RateOfClimb
	}
	return 0
}

var File_track_proto protoreflect.FileDescriptor

const file_track_proto_rawDesc = "" +
	"\n" +
	"\vtrack.proto\x12\x03utm\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xbb\b\n" +
	"\x05Track\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\x12\x1f\n" +
	"\vprovider_id\x18\v \x01(\tR\n" +
	"providerId\x12\x1b\n" +
	"\tsource_id\x18\f \x01(\tR\bsourceId\x12)\n" +
	"\x10asterix_category\x18\x0e \x01(\tR\x0fasterixCategory\x12\x19\n" +
	"\btrack_id\x18\x15 \x01(\tR\atrackId\x12\x1a\n" +
	"\bcallsign\x18\x16 \x01(\tR\bcallsign\x128\n" +
	"\x18icao_aircraft_descriptor\x18\x17 \x01(\tR\x16icaoAircraftDescriptor\x12#\n" +
	"\raircraft_type\x18\x18 \x01(\tR\faircraftType\x127\n" +
	"\x10emitter_category\x18\x19 \x01(\x0e2\f.utm.EmitterR\x0femitterCategory\x128\n" +
	"\ttimestamp\x18\x1f \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12+\n" +
	"\bposition\x18) \x01(\v2\x0f.utm.CoordinateR\bposition\x12.\n" +
	"\vvelocity_ms\x18* \x01(\v2\r.utm.VelocityR\n" +
	"velocityMs\x12$\n" +
	"\x0egroud_speed_ms\x18+ \x01(\x01R\fgroudSpeedMs\x12*\n" +
	"\x11vertical_speed_ms\x18, \x01(\x01R\x0fverticalSpeedMs\x12'\n" +
	"\x0fheading_degrees\x18- \x01(\x01R\x0eheadingDegrees\x124\n" +
	"\baccuracy\x182 \x01(\v2\x13.utm.Track.AccuracyH\x00R\baccuracy\x88\x01\x01\x1a\x92\x03\n" +
	"\bAccuracy\x12\x1d\n" +
	"\n" +
	"position_x\x18\x01 \x01(\x01R\tpositionX\x12\x1d\n" +
	"\n" +
	"position_y\x18\x02 \x01(\x01R\tpositionY\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12-\n" +
	"\x12geometric_altitude\x18\x05 \x01(\x01R\x11geometricAltitude\x12/\n" +
	"\x13barometric_altitude\x18\x06 \x01(\x01R\x12barometricAltitude\x12\x1d\n" +
	"\n" +
	"velocity_x\x18\a \x01(\x01R\tvelocityX\x12\x1d\n" +
	"\n" +
	"velocity_y\x18\b \x01(\x01R\tvelocityY\x12%\n" +
	"\x0eacceleration_x\x18\t \x01(\x01R\raccelerationX\x12%\n" +
	"\x0eacceleration_y\x18\n" +
	" \x01(\x01R\raccelerationY\x12\"\n" +
	"\rrate_of_climb\x18\v \x01(\x01R\vrateOfClimbB\v\n" +
	"\t_accuracy\"4\n" +
	"\bVelocity\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x01R\x01z\"\x8f\x01\n" +
	"\n" +
	"Coordinate\x12)\n" +
	"\x10latitude_degrees\x18\x01 \x01(\x01R\x0flatitudeDegrees\x12+\n" +
	"\x11longitude_degrees\x18\x02 \x01(\x01R\x10longitudeDegrees\x12)\n" +
	"\baltitude\x18\x03 \x01(\v2\r.utm.AltitudeR\baltitude\"\x92\x02\n" +
	"\bAltitude\x12\x16\n" +
	"\x06meters\x18\x03 \x01(\x01R\x06meters\x125\n" +
	"\treference\x18\x04 \x01(\x0e2\x17.utm.Altitude.ReferenceR\treference\"\xb6\x01\n" +
	"\tReference\x12\x15\n" +
	"\x11REFERENCE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13REFERENCE_ELLIPSOID\x10\x01\x12\x13\n" +
	"\x0fREFERENCE_GEOID\x10\x02\x12\x15\n" +
	"\x11REFERENCE_SURFACE\x10\x03\x12\x16\n" +
	"\x12REFERENCE_EXTERNAL\x10\x04\x12\x1b\n" +
	"\x17REFERENCE_STANDARD_BARO\x10\x05\x12\x18\n" +
	"\x14REFERENCE_LOCAL_BARO\x10\x06*\x89\x04\n" +
	"\aEmitter\x12\x13\n" +
	"\x0fEMITTER_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16EMITTER_LIGHT_AIRCRAFT\x10\x01\x12\x1a\n" +
	"\x16EMITTER_SMALL_AIRCRAFT\x10\x02\x12\x1b\n" +
	"\x17EMITTER_MEDIUM_AIRCRAFT\x10\x03\x12\x1a\n" +
	"\x16EMITTER_LARGE_AIRCRAFT\x10\x04\x12\x19\n" +
	"\x15EMITTER_HEAVY_AIRCAFT\x10\x05\x12\x1f\n" +
	"\x1bEMITTER_HIGHLY_MANUEVERABLE\x10\x06\x12\x16\n" +
	"\x12EMITTER_ROTORCRAFT\x10\n" +
	"\x12\x12\n" +
	"\x0eEMITTER_GLIDER\x10\v\x12\x1c\n" +
	"\x18EMITTER_LIGHTER_THAN_AIR\x10\f\x12\x0f\n" +
	"\vEMITTER_UAV\x10\r\x12\x11\n" +
	"\rEMITTER_SPACE\x10\x0e\x12\x16\n" +
	"\x12EMITTER_ULTRALIGHT\x10\x0f\x12\x17\n" +
	"\x13EMITTER_PARACHUTIST\x10\x10\x12!\n" +
	"\x1dEMITTER_SFC_EMERGENCY_VEHICLE\x10\x14\x12\x1f\n" +
	"\x1bEMITTER_SFC_SERVICE_VEHICLE\x10\x15\x12\x18\n" +
	"\x14EMITTER_SFC_OBSTACLE\x10\x16\x12 \n" +
	"\x1cEMITTER_SFC_OBSTACLE_CLUSTER\x10\x17\x12\x1d\n" +
	"\x19EMITTER_SFC_OBSTACLE_LINE\x10\x182J\n" +
	"\x10TrafficCollector\x126\n" +
	"\x0eCollectTraffic\x12\n" +
	".utm.Track\x1a\x16.google.protobuf.Empty(\x01B-Z+github.com/skyguide-ansp/utm-interfaces/utmb\x06proto3"

var (
	file_track_proto_rawDescOnce sync.Once
	file_track_proto_rawDescData []byte
)

func file_track_proto_rawDescGZIP() []byte {
	file_track_proto_rawDescOnce.Do(func() {
		file_track_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_track_proto_rawDesc), len(file_track_proto_rawDesc)))
	})
	return file_track_proto_rawDescData
}

var file_track_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_track_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_track_proto_goTypes = []any{
	(Emitter)(0),                  // 0: utm.Emitter
	(Altitude_Reference)(0),       // 1: utm.Altitude.Reference
	(*Track)(nil),                 // 2: utm.Track
	(*Velocity)(nil),              // 3: utm.Velocity
	(*Coordinate)(nil),            // 4: utm.Coordinate
	(*Altitude)(nil),              // 5: utm.Altitude
	(*Track_Accuracy)(nil),        // 6: utm.Track.Accuracy
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_track_proto_depIdxs = []int32{
	0, // 0: utm.Track.emitter_category:type_name -> utm.Emitter
	7, // 1: utm.Track.timestamp:type_name -> google.protobuf.Timestamp
	4, // 2: utm.Track.position:type_name -> utm.Coordinate
	3, // 3: utm.Track.velocity_ms:type_name -> utm.Velocity
	6, // 4: utm.Track.accuracy:type_name -> utm.Track.Accuracy
	5, // 5: utm.Coordinate.altitude:type_name -> utm.Altitude
	1, // 6: utm.Altitude.reference:type_name -> utm.Altitude.Reference
	2, // 7: utm.TrafficCollector.CollectTraffic:input_type -> utm.Track
	8, // 8: utm.TrafficCollector.CollectTraffic:output_type -> google.protobuf.Empty
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_track_proto_init() }
func file_track_proto_init() {
	if File_track_proto != nil {
		return
	}
	file_track_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_track_proto_rawDesc), len(file_track_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_track_proto_goTypes,
		DependencyIndexes: file_track_proto_depIdxs,
		EnumInfos:         file_track_proto_enumTypes,
		MessageInfos:      file_track_proto_msgTypes,
	}.Build()
	File_track_proto = out.File
	file_track_proto_goTypes = nil
	file_track_proto_depIdxs = nil
}
